# standard defines
GCC =   gcc
LD  =   gcc
AR	=	ar rcs
RM  =   /bin/rm -f

# debug or release
PSTATUS = debug
# lstatic or lshared
MODULE = lshared

# default cflags
ifeq ($(PSTATUS), debug)
	CFLAGS := -Wall -Wextra -O0 -ansi -pedantic -g
else
	CFLAGS := -Wall -Wextra -O3 -ansi -pedantic -DNDEBUG
endif

