# common variables
GCC = gcc
LD = gcc
RM = rm -f
AR = ar rcs

# default cflags
ifeq ($(PSTATUS), debug)
	CFLAGS := -Wall -Wextra -O0 -g
	STRIP = @echo Debug-built
else
	CFLAGS := -Wall -Wextra -O3 -DNDEBUG
	STRIP = strip
endif
